version: '3.8'

services:
  trading_bot:
    build: .
    container_name: binance_trading_bot
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
    environment:
      - TZ=America/Sao_Paulo
      - API_KEY=${BINANCE_API_KEY}
      - API_SECRET=${BINANCE_API_SECRET}
      - TESTNET=${TESTNET:-true}
